admin = User.create(:username => "admin", :email => "admin@movieguru.com", :password => "admin", :is_admin => "true")

Movie.create(:title => "Big Hero 6 (2014)", :trailer => "https://www.youtube.com/embed/z3biFxZIJOQ", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/big-hero-six-poster2.jpg", :year_released => 2014, :summary => "Robotics prodigy Hiro (Ryan Potter) lives in the city of San Fransokyo. Next to his older brother, Tadashi, Hiro's closest companion is Baymax (Scott Adsit), a robot whose sole purpose is to take care of people. When a devastating turn of events throws Hiro into the middle of a dangerous plot, he transforms Baymax and his other friends, Go Go Tamago (Jamie Chung), Wasabi (Damon Wayans Jr.), Honey Lemon (Genesis Rodriguez) and Fred (T.J. Miller) into a band of high-tech heroes.")

Movie.create(:title => "The Pursuit of Happyness (2006)", :trailer => "https://www.youtube.com/embed/DMOBlEcRuw8", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/pursuit-of-happyness-poster.jpg", :year_released => 2006, :summary => "Life is a struggle for single father Chris Gardner (Will Smith). Evicted from their apartment, he and his young son (Jaden Christopher Syre Smith) find themselves alone with no place to go. Even though Chris eventually lands a job as an intern at a prestigious brokerage firm, the position pays no money. The pair must live in shelters and endure many hardships, but Chris refuses to give in to despair as he struggles to create a better life for himself and his son.")

Movie.create(:title => "Black Panther (2018)", :trailer => "https://www.youtube.com/embed/xjDjIWPwcPU",  :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/Black-Panther-poster-main-xl.jpg", :year_released => 2018, :summary => "\"Black Panther\" follows T'Challa who, after the events of \"Captain America: Civil War,\" returns home to the isolated, technologically advanced African nation of Wakanda to take his place as King. However, when an old enemy reappears on the radar, T'Challa's mettle as King and Black Panther is tested when he is drawn into a conflict that puts the entire fate of Wakanda and the world at risk.")

Movie.create(:title => "Avatar (2009)", :trailer => "https://www.youtube.com/embed/5PSNL1qE6VY", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/avatar-poster2_thumb.jpg", :year_released => 2009, :summary =>"A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.")

Movie.create(:title => "The Dark Knight (2008)", :trailer => "https://www.youtube.com/embed/EXeTwQWrcwY", :img => "https://www.joblo.com/movie-posters/2008/the-dark-knight/image-19776", :year_released => 2008, :summary =>"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.")

Movie.create(:title => "Avengers: Infinity War (2018)", :trailer => "https://www.youtube.com/embed/6ZfuNTqbHE8", :img => "https://www.joblo.com/movie-posters/2018/avengers-infinity-war/image-34547", :year_released => 2018, :summary =>"The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.")

Movie.create(:title => "Avengers: Endgame (2019)", :trailer => "https://www.youtube.com/embed/TcMBFSGVi1c", :img => "https://www.joblo.com/assets/images/joblo/posters/2019/03/avengers-endgame-poster-xl.jpg", :year_released => 2019, :summary =>"After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.")

Movie.create(:title => "Ocean's Eleven (2001)", :trailer => "https://www.youtube.com/embed/n3epi9hPbqQ", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/2001-poster-oceans_eleven-3.jpg", :year_released => 2001, :summary =>"Danny Ocean and his ten accomplices plan to rob three Las Vegas casinos simultaneously.")

Movie.create(:title => "Mission: Impossible - Fallout (2018)", :trailer => "https://www.youtube.com/embed/wb49-oV0F78", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/mission-fallout-poster-xl.jpg", :year_released => 2018, :summary =>"Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.")

Movie.create(:title => "Jerry Maguire (1996)", :trailer => "https://www.youtube.com/embed/rCCaTPY-z4Q", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/1996-jerry-maguire-poster1.jpg", :year_released => 1996, :summary =>"When a sports agent has a moral epiphany and is fired for expressing it, he decides to put his new philosophy to the test as an independent agent with the only athlete who stays with him and his former colleague.")

Movie.create(:title => "Top Gun (1986)", :trailer => "https://www.youtube.com/embed/xa_z57UatDY", :img => "https://www.joblo.com/assets/images/joblo/posters/2019/12/top-gun-maverick_poster.jpg", :year_released => 1986, :summary =>"As students at the United States Navy's elite fighter weapons school compete to be best in the class, one daring young pilot learns a few things from a civilian instructor that are not taught in the classroom.")

Movie.create(:title => "Titanic (1997)", :trailer => "https://www.youtube.com/embed/2e-eXJ6HgkQ", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/titanic3d-poster1.jpg", :year_released => 1997, :summary =>"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.")

Movie.create(:title => "The Wolf of Wall Street (2013)", :trailer => "https://www.youtube.com/embed/iszwuX1AK6A", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/wolf-of-wall-street-poster1.jpg", :year_released => 2013, :summary =>"Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.")

Movie.create(:title => "Forrest Gump (1994)", :trailer => "https://www.youtube.com/embed/bLvqoHBptjg", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/1994-forrest-gump-1.jpg", :year_released => 1994, :summary =>"The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.")

Movie.create(:title => "Cast Away (2000)", :trailer => "https://www.youtube.com/embed/qGuOZPwLayY", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/2000-poster-cast_away-1.jpg", :year_released => 2000, :summary =>"A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.")

Movie.create(:title => "Saving Private Ryan (1998)", :trailer => "https://www.youtube.com/embed/RYID71hYHzg", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/1998-poster-saving_private_ryan-2.jpg", :year_released => 1998, :summary =>"Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.")

Movie.create(:title => "Wonder Woman (2017)", :trailer => "https://www.youtube.com/embed/1Q8fG0TtVAY", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/wonder-woman-new-poster_thumb.jpg", :year_released => 2017, :summary =>"When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.")

Movie.create(:title => "Moana (2016)", :trailer => "https://www.youtube.com/embed/LKFuXETZUsI", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/moana-poster_thumb.jpg", :year_released => 2016, :summary =>"In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call to seek out the Demigod to set things right.")

Movie.create(:title => "The Fast and the Furious (2001)", :trailer => "https://www.youtube.com/embed/2TAOizOnNPo", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/fast-and-the-furious-poster.jpg", :year_released => 2001, :summary =>"Los Angeles police officer Brian O'Conner must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to destroy.")

Movie.create(:title => "The Fate of the Furious (2017)", :trailer => "https://www.youtube.com/embed/JwMKRevYa_M", :img => "https://www.joblo.com/assets/images/oldsite/posters/images/full/tfotf-sapposter-gallery.jpg", :year_released => 2017, :summary =>"When a mysterious woman seduces Dominic Toretto into the world of terrorism and a betrayal of those closest to him, the crew face trials that will test them as never before.")
